version = 0.1
[default.deploy.parameters]
resolve_s3 = true
s3_prefix = "swa-bot"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
disable_rollback = true
parameter_overrides = "ExecutionRole=\"ExecutionRole\""
image_repositories = []
